### ISSUE TITLE
Rectangle lines are not visible

### ISSUE THREAD

**Issue by nedushny** [Kuama-IT/android-document-scanner#11]
![image](https://user-images.githubusercontent.com/71440998/173816673-79940ea5-e094-4d7b-9e16-c9bf5dbe672e.png)

How i can draw the lines of rectangle?

**Comment by giovanni-nic-kuama** [comment]
The rectangle is shown only on the camera view, not on the Photo View (the one you posted on the screen) which only show the corners of the rectangle that it has found. The main problem here is that you are not scanning a document so the algorithm will never show a rectangle. If you want to really try the document scanner you should setup the Virtual Scene on the emulator ([here](https://developers.google.com/ar/develop/c/emulator)) and put a document on the scene (or use a real device).
