### ISSUE TITLE
HELP! I also want to make such app. please guide

### ISSUE THREAD

**Issue by Karan326** [Kuama-IT/android-document-scanner#2]
Sir I also want to make such app, could you please tell how should I proceed?
Is there any tutorial for for it?
Please help sir

**Comment by doseeare** [comment]
Hello, for start i think you can try ML Kit

**Comment by giovanni-nic-kuama** [comment]
The Readme has all the necessary info. You just need to create a new App from android studio, add the requested dependency, and implement it on a Activity.
